# ===============================
# common
# ===============================

# 일반 상수

app:
  domain: ${APP_DOMAIN:}

file:
  domain: ${FILE_DOMAIN:}
  dir: ${FILE_DIR:}
  handler: ${FILE_HANDLER:}

payment:
  portone:
    api-key: ${PORTONE_API_KEY:}
    api-secret: ${PORTONE_API_SECRET:}
    id-code: ${PORTONE_ID_CODE:}

aws:
  cloudfront:
    domain: ${AWS_CLOUDFRONT_DOMAIN:}
    key-pair-id: ${AWS_CLOUDFRONT_KEY_PAIR_ID:}
    private-key: ${AWS_CLOUDFRONT_PRIVATE_KEY:}
    signed-cookie:
      expire-min: 60
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME:}





